### ISSUE TITLE
Get a list of Pro names and convert it into an array.

### ISSUE THREAD

**Issue by yongzhihuang** [yongzhihuang/teemofy#1]
Get list of names here: http://lol.gamepedia.com/Players_(All)

Just their ID is needed. You're welcome to use scripts to scrape and merge this (HAVE FUN)

Convert them to an array and store it in the `playerNames` variable.
https://github.com/yongzhihuang/teemofy/blob/master/src/inject/inject.js#L6

**Comment by mridulg** [comment]
@yongzhihuang, on it.
